### ISSUE TITLE
Assertion Error while running tests on head

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#35] opened 2016-04-14 15:16 UTC
Hi there,

Sorry if you're already aware of this but I get the following error while running `sigh` in the folder of a freshly cloned copy of this repo.

```
    ✓ detects changes to two files matching globbed pattern (841ms)
{ type: 'add',
  path: 'test/tmp/sigh-glob-test-116314-89000-xytzgj/file1.js',
  initPhase: true,
  opTreeIndex: 4,
  createTime: Thu Apr 14 2016 17:13:44 GMT+0200 (CEST) }
{ type: 'add',
  path: 'test/tmp/sigh-glob-test-116314-89000-xytzgj/file2.js',
  initPhase: true,
  opTreeIndex: 4,
  createTime: Thu Apr 14 2016 17:13:44 GMT+0200 (CEST) }
{ type: 'change',
  path: 'test/tmp/sigh-glob-test-116314-89000-xytzgj/file2.js',
  initPhase: false,
  opTreeIndex: 4,
  createTime: Thu Apr 14 2016 17:13:44 GMT+0200 (CEST) }
{ type: 'change',
  path: 'test/tmp/sigh-glob-test-116314-89000-xytzgj/file1.js',
  initPhase: false,
  opTreeIndex: 4,
  createTime: Thu Apr 14 2016 17:13:44 GMT+0200 (CEST) }

xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:368
          after();
          ^
AssertionError: expected [ Array(2) ] to deeply equal [ Array(1) ]
    at xxx/sigh/src/test/plugin/glob.spec.js:143:28
    at xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:980:16
    at xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:395:23
    at Object.Bacon.UpdateBarrier.inTransaction (xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:368:11)
    at Dispatcher.push (xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:1142:24)
    at Dispatcher.handleEvent (xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:1195:17)
    at xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:232:17
    at xxx/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:1715:17
    at [object Object].sender [as _onTimeout] (xxxI/sigh/node_modules/sigh-core/node_modules/baconjs/dist/Bacon.js:2148:14)
    at Timer.listOnTimeout (timers.js:92:15)
 ! error: pipeline mocha
 ! Error: killed
```

**Comment by ohjames** [comment] 2016-04-17 13:39
Was this on Mac OS X? That test seems to run much slower on that system... the code has to use a debounce to work around a bug in the fs watcher it uses, that makes the test sensitive to time.

**Comment by ohjames** [comment] 2016-04-17 13:40
Duplicate of #11

**Closed** 2016-04-17 13:40 UTC
Labels: invalid

**Comment by ohjames** [comment] 2016-06-17 17:57
#11 is fixed now.
